

/* =============== LOGIN ================= */
// LOGS THE USER IN USING FACEBOOK API, REDIRECTS TO EITHER 'create-route' OR 'current-route' SCREEN DEPENDING IF THE USER'S ACCOUNT ALREADY HAS
// AN ONGOING ROUTE ASSOCIATED WITH IT.
// GET - /LOGIN


/* =========== ROUTE ENDPOINTS =========== */
// CREATES A ROUTE
// POST -/ID:/ROUTE

// GETS A ROUTE
// GET -/ID:/ROUTE

// UPDATES A ROUTE'S GEOLOCATION DATA !OR! SOCKETS
// PUT -/ID:/ROUTE !OR! SOCKETS

/* ================ USER ENDPOINTS ================ */
// GET USER STATS
// GET -/ID:/SETTINGS

// CREATE NEW CONTACTS
// POST -/ID:/SETTINGS

// UPDATES USER STATS
// PUT -/ID:/SETTINGS

