

/* =============== LOGIN ================= */
// LOGS THE USER IN USING FACEBOOK API, REDIRECTS TO EITHER 'create-route' OR 'current-route' SCREEN DEPENDING IF THE USER'S ACCOUNT ALREADY HAS
// AN ONGOING ROUTE ASSOCIATED WITH IT.
// POST - /LOGIN


/* =========== TRIP ENDPOINTS =========== */
// CREATES A TRIP
// POST -USERS/USER_ID:/TRIPS/TRIP_ID

// GETS A TRIP
// GET -USERS/USER_ID:/TRIPS/TRIP_ID

// UPDATES A TRIP'S GEOLOCATION DATA !OR! SOCKETS
// PUT -USERS/USER_ID:/TRIPS/TRIP_ID !OR! SOCKETS

// MARKS A TRIP AS 'active: false'
// DELETE -USERS/USER_ID:/TRIPS/TRIP_ID

/* ================ USER ENDPOINTS ================ */
// GET USER STATS
// GET -USER/USER_ID:

// CREATE NEW CONTACTS
// POST -USER/USER_ID:

// UPDATES USER STATS
// PUT -/ID:/SETTINGS

